//! User-facing stats strings in one place.
//!
//! Every literal the stats renderers show to chat participants lives here so
//! a future locale is a new constructor, not a hunt through `format!` calls.
//! Values (numbers, links, dates) are still formatted at the call site; only
//! the fixed wording is centralized.

/// All participant-facing stats wording. Field docs note the call sites.
pub struct StatsStrings {
    // Periods.
    pub period_day: &'static str,
    pub period_week: &'static str,
    pub period_month: &'static str,
    // Report frames.
    pub report_title: &'static str,
    pub period_since: &'static str,
    pub all_time: &'static str,
    pub no_data: &'static str,
    pub not_available: &'static str,
    // Summary rows.
    pub messages: &'static str,
    pub active_users: &'static str,
    pub replies: &'static str,
    pub links: &'static str,
    pub media: &'static str,
    pub channel_posts: &'static str,
    pub bot_comments: &'static str,
    pub bot_replies: &'static str,
    pub reaction_events: &'static str,
    pub reaction_count_updates: &'static str,
    pub bot_comment_reactions: &'static str,
    pub joins: &'static str,
    pub leaves: &'static str,
    pub joins_leaves: &'static str,
    pub per_active: &'static str,
    pub reply_share: &'static str,
    pub sentiment_mood: &'static str,
    pub sentiment_unknown: &'static str,
    pub sentiment_positive: &'static str,
    // Attraction block.
    pub attraction: &'static str,
    pub window_5m: &'static str,
    pub window_30m: &'static str,
    pub window_24h: &'static str,
    pub people_30m: &'static str,
    pub messages_unit: &'static str,
    // Rankings.
    pub top_users: &'static str,
    pub top_writers: &'static str,
    pub quiet_ones: &'static str,
    pub top_word_usage: &'static str,
    pub word_occurrences: &'static str,
    pub top_reacted_messages: &'static str,
    pub messages_unit_short: &'static str,
    pub replies_unit_short: &'static str,
    pub links_unit_short: &'static str,
    pub media_unit_short: &'static str,
    // Bot comments block.
    pub bot_comments_title: &'static str,
    // User card.
    pub user_stats_title: &'static str,
    pub profile_not_found_title: &'static str,
    pub user_not_found_hint: &'static str,
    pub user_target_hint: &'static str,
    pub user_target_hint_short: &'static str,
    pub status_updated: &'static str,
    pub no_timestamp: &'static str,
    pub first_message: &'static str,
    pub last_message: &'static str,
    pub comments: &'static str,
    pub voices: &'static str,
    pub active_days: &'static str,
    pub reactions_given: &'static str,
    pub reactions_received: &'static str,
    pub name_row: &'static str,
    pub moderation_row: &'static str,
    pub tag_row: &'static str,
    pub frequent_words: &'static str,
    // Moderation summary.
    pub unknown_measure: &'static str,
    pub ban_label: &'static str,
    pub mute_label: &'static str,
    pub until_utc: &'static str,
    pub forever: &'static str,
    pub no_active_restrictions: &'static str,
    pub moderation_line: &'static str,
    pub warnings: &'static str,
    // Message preview fallbacks.
    pub message_without_text: &'static str,
    pub media_prefix: &'static str,
    pub media_photo: &'static str,
    pub media_video: &'static str,
    pub media_file: &'static str,
    pub media_audio: &'static str,
    pub media_voice: &'static str,
    pub media_sticker: &'static str,
    pub media_gif: &'static str,
    pub chat_fallback_label: &'static str,
    pub days_ago: &'static str,
    // Rich-dialect tables and details blocks.
    pub col_number: &'static str,
    pub col_who: &'static str,
    pub col_messages_short: &'static str,
    pub col_reactions: &'static str,
    pub col_media_voice: &'static str,
    pub col_links: &'static str,
    pub col_post: &'static str,
    pub col_window_30m: &'static str,
    pub col_author: &'static str,
    pub col_heart: &'static str,
    pub col_open: &'static str,
    pub col_link: &'static str,
    pub col_text: &'static str,
    pub details_summary: &'static str,
    pub details_attraction: &'static str,
    pub details_top_users: &'static str,
    pub details_bot_comments: &'static str,
    pub details_main: &'static str,
    pub details_activity: &'static str,
    pub details_extra: &'static str,
    pub details_previews: &'static str,
    pub top_reactions_short: &'static str,
    pub message_link_label: &'static str,
    pub reactions_pair: &'static str,
    pub comments_pair: &'static str,
    pub media_voice_pair: &'static str,
    pub footer_tables: &'static str,
    pub footer_clickable: &'static str,
    pub footer_compact: &'static str,
    pub window_col: &'static str,
    pub average_col: &'static str,
    pub minutes_5: &'static str,
    pub minutes_30: &'static str,
    pub hours_24: &'static str,
    pub comments_table_reply: &'static str,
    pub comments_table_reactions: &'static str,
    pub comments_table_comment: &'static str,
    pub reactions_row: &'static str,
    pub received_verb: &'static str,
    pub per_30m_unit: &'static str,
    pub reactions_dash: &'static str,
    pub row_reply: &'static str,
    pub active_by_day: &'static str,
    pub avg_word: &'static str,
    pub max_word: &'static str,
    pub returns: &'static str,
    pub engagement: &'static str,
}

use crate::features::stats::types::StatsPeriod;

impl StatsStrings {
    pub fn russian() -> Self {
        Self {
            period_day: "день",
            period_week: "неделю",
            period_month: "месяц",
            report_title: "Статистика за",
            period_since: "Период с",
            all_time: "За всё время",
            no_data: "Нет данных.",
            not_available: "—",
            messages: "Сообщения",
            active_users: "Активные пользователи",
            replies: "Реплаи",
            links: "ссылки",
            media: "медиа",
            channel_posts: "Посты канала",
            bot_comments: "комменты бота",
            bot_replies: "Реплаи на бота",
            reaction_events: "Реакции events",
            reaction_count_updates: "count updates",
            bot_comment_reactions: "Реакции на комменты бота",
            joins: "Входы",
            leaves: "выходы",
            joins_leaves: "Входы / выходы",
            per_active: "Сообщений на активного",
            reply_share: "Доля реплаев",
            sentiment_mood: "Настроение реакций",
            sentiment_unknown: "неизвестно",
            sentiment_positive: "позитив",
            attraction: "Завлечение после коммента",
            window_5m: "5м",
            window_30m: "30м",
            window_24h: "24ч",
            people_30m: "людей 30м",
            messages_unit: "сообщений",
            top_users: "Топ пользователей",
            top_writers: "Топ пишущих",
            quiet_ones: "Тихони чата",
            top_word_usage: "Топ употреблений слова",
            word_occurrences: "вхождений",
            top_reacted_messages: "Топ сообщений по реакциям",
            messages_unit_short: "соо",
            replies_unit_short: "реплаев",
            links_unit_short: "ссылок",
            media_unit_short: "медиа",
            bot_comments_title: "Комменты бота",
            user_stats_title: "Статистика пользователя",
            profile_not_found_title: "Профиль не найден",
            user_not_found_hint: "Не нашёл пользователя. Используй id, username из уже виденных ботом пользователей или reply на сообщение.",
            user_target_hint: "Не понял, кого смотреть. Отправь команду обычным сообщением, ответь ей на сообщение пользователя или передай id/username.",
            user_target_hint_short: "Не понял, кого смотреть. Передай id, username или reply на сообщение.",
            status_updated: "Статус обновлён",
            no_timestamp: "нет данных",
            first_message: "Первое сообщение",
            last_message: "Последнее сообщение",
            comments: "Комментарии",
            voices: "голосовые",
            active_days: "Активных дней",
            reactions_given: "Реакций поставил",
            reactions_received: "Реакций получил",
            name_row: "имя",
            moderation_row: "модерация",
            tag_row: "тег",
            frequent_words: "частые слова",
            unknown_measure: "неопределённая мера — нужна сверка",
            ban_label: "бан",
            mute_label: "мут",
            until_utc: "до",
            forever: "навсегда",
            no_active_restrictions: "активных ограничений нет",
            moderation_line: "Модерация",
            warnings: "предупреждений",
            message_without_text: "сообщение без текста",
            media_prefix: "медиа",
            media_photo: "фото",
            media_video: "видео",
            media_file: "файл",
            media_audio: "аудио",
            media_voice: "голосовое",
            media_sticker: "стикер",
            media_gif: "GIF",
            chat_fallback_label: "чат",
            days_ago: "дн. назад",
            col_number: "#",
            col_who: "Кто",
            col_messages_short: "Соо",
            col_reactions: "Реакции",
            col_media_voice: "Медиа / voice",
            col_links: "Ссылки",
            col_post: "Пост",
            col_window_30m: "30м",
            col_author: "Автор",
            col_heart: "❤",
            col_open: "Открыть",
            col_link: "Ссылка",
            col_text: "Текст",
            details_summary: "Сводка периода",
            details_attraction: "Завлечение после комментария",
            details_top_users: "Топ пользователей",
            details_bot_comments: "Комментарии бота",
            details_main: "Основное",
            details_activity: "Активность",
            details_extra: "Дополнительно",
            details_previews: "Превью сообщений",
            top_reactions_short: "Топ реакций",
            message_link_label: "сообщение",
            reactions_pair: "поставил",
            comments_pair: "комментарии / боту",
            media_voice_pair: "медиа / voice",
            footer_tables: "Rich-версия построена из общей модели данных: таблицы, секции и кликабельные профили.",
            footer_clickable: "Имена кликабельны, основная таблица короткая; расширенные метрики спрятаны ниже.",
            footer_compact: "Автор и сообщение кликабельны; тексты спрятаны, чтобы топ не превращался в простыню.",
            window_col: "Окно",
            average_col: "Среднее",
            minutes_5: "5 минут",
            minutes_30: "30 минут",
            hours_24: "24 часа",
            comments_table_reply: "Reply",
            comments_table_reactions: "Реакции",
            comments_table_comment: "Комментарий",
            reactions_row: "реакции",
            received_verb: "получил",
            per_30m_unit: "соо за 30м",
            reactions_dash: "реакций -",
            row_reply: "reply",
            active_by_day: "Активность по дням",
            avg_word: "сред",
            max_word: "макс",
            returns: "Возвраты",
            engagement: "Вовлечённость",
        }
    }
    /// Period name for report titles. Kept here (not on the enum) so a
    /// future locale replaces wording without touching data types.
    pub fn period_title(&self, period: StatsPeriod) -> &'static str {
        match period {
            StatsPeriod::Day => self.period_day,
            StatsPeriod::Week => self.period_week,
            StatsPeriod::Month => self.period_month,
        }
    }

    /// Locale entry point for report wiring. Unknown locales fall back to
    /// Russian; startup validation rejects anything but `ru`/`en`.
    pub fn for_locale(locale: &str) -> Self {
        match locale {
            "en" => Self::english(),
            _ => Self::russian(),
        }
    }
    /// English wording with identical layout contracts: same fields, same
    /// value formats, only the fixed labels change.
    pub fn english() -> Self {
        Self {
            period_day: "day",
            period_week: "week",
            period_month: "month",
            report_title: "Stats for",
            period_since: "Period since",
            all_time: "All time",
            no_data: "No data.",
            not_available: "—",
            messages: "Messages",
            active_users: "Active users",
            replies: "Replies",
            links: "links",
            media: "media",
            channel_posts: "Channel posts",
            bot_comments: "bot comments",
            bot_replies: "Bot replies",
            reaction_events: "Reaction events",
            reaction_count_updates: "count updates",
            bot_comment_reactions: "Reactions on bot comments",
            joins: "Joins",
            leaves: "leaves",
            joins_leaves: "Joins / leaves",
            per_active: "Messages per active user",
            reply_share: "Reply share",
            sentiment_mood: "Reaction mood",
            sentiment_unknown: "unknown",
            sentiment_positive: "positive",
            attraction: "Pull after comment",
            window_5m: "5m",
            window_30m: "30m",
            window_24h: "24h",
            people_30m: "people 30m",
            messages_unit: "messages",
            top_users: "Top users",
            top_writers: "Top writers",
            quiet_ones: "Quiet ones",
            top_word_usage: "Top users by word usage",
            word_occurrences: "occurrences",
            top_reacted_messages: "Top reacted messages",
            messages_unit_short: "msgs",
            replies_unit_short: "replies",
            links_unit_short: "links",
            media_unit_short: "media",
            bot_comments_title: "Bot comments",
            user_stats_title: "User stats",
            profile_not_found_title: "Profile not found",
            user_not_found_hint: "User not found. Use an id, a username the bot has already seen, or reply to a message.",
            user_target_hint: "Unclear whose stats to show. Send the command as a plain message, reply it to a user message, or pass an id/username.",
            user_target_hint_short: "Unclear whose stats to show. Pass an id, username, or a message reply.",
            status_updated: "Status updated",
            no_timestamp: "no data",
            first_message: "First message",
            last_message: "Last message",
            comments: "Comments",
            voices: "voices",
            active_days: "Active days",
            reactions_given: "Reactions given",
            reactions_received: "Reactions received",
            name_row: "name",
            moderation_row: "moderation",
            tag_row: "tag",
            frequent_words: "frequent words",
            unknown_measure: "unknown measure — needs review",
            ban_label: "ban",
            mute_label: "mute",
            until_utc: "until",
            forever: "forever",
            no_active_restrictions: "no active restrictions",
            moderation_line: "Moderation",
            warnings: "warnings",
            message_without_text: "message without text",
            media_prefix: "media",
            media_photo: "photo",
            media_video: "video",
            media_file: "file",
            media_audio: "audio",
            media_voice: "voice",
            media_sticker: "sticker",
            media_gif: "GIF",
            chat_fallback_label: "chat",
            days_ago: "days ago",
            row_reply: "reply",
            col_number: "#",
            col_who: "Who",
            col_messages_short: "Msgs",
            col_reactions: "Reactions",
            col_media_voice: "media / voice",
            col_links: "Links",
            col_post: "Post",
            col_window_30m: "30m",
            col_author: "Author",
            col_heart: "❤",
            col_open: "Open",
            col_link: "Link",
            col_text: "Text",
            details_summary: "Period summary",
            details_attraction: "Pull after comment",
            details_top_users: "Top users",
            details_bot_comments: "Bot comments",
            details_main: "Profile",
            details_activity: "Activity",
            details_extra: "More",
            details_previews: "Message previews",
            top_reactions_short: "Top reactions",
            message_link_label: "message",
            reactions_pair: "given",
            comments_pair: "comments / to bot",
            media_voice_pair: "media / voice",
            footer_tables: "Rich version built from the shared data model: tables, sections, clickable profiles.",
            footer_clickable: "Names are clickable, the main table is short; extended metrics are below.",
            footer_compact: "Author and message are clickable; texts are hidden to keep the top compact.",
            window_col: "Window",
            average_col: "Average",
            minutes_5: "5 minutes",
            minutes_30: "30 minutes",
            hours_24: "24 hours",
            comments_table_reply: "Reply",
            comments_table_reactions: "Reactions",
            comments_table_comment: "Comment",
            reactions_row: "reactions",
            received_verb: "received",
            per_30m_unit: "msgs per 30m",
            reactions_dash: "reactions -",
            active_by_day: "Daily activity",
            avg_word: "avg",
            max_word: "max",
            returns: "Returns",
            engagement: "Engagement",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn russian_strings_are_nonempty() {
        let strings = StatsStrings::russian();
        for label in [
            strings.report_title,
            strings.messages,
            strings.top_writers,
            strings.quiet_ones,
            strings.user_stats_title,
            strings.moderation_line,
        ] {
            assert!(!label.trim().is_empty());
        }
    }

    #[test]
    fn english_renders_parallel_report() {
        use crate::features::stats::document::{Kv, Section};

        let strings = StatsStrings::english();
        assert_eq!(
            strings.period_title(crate::features::stats::types::StatsPeriod::Week),
            "week"
        );
        let section = Section {
            title: Some(strings.top_writers),
            rows: vec![Kv {
                label: strings.messages,
                value: "<b>5</b>".to_string(),
            }],
        };
        let html = section.emit_html();
        assert!(html.contains("Top writers"));
        assert!(html.contains("Messages: <b>5</b>"));
        assert!(!html.contains("Топ"));
    }
}
